import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  Book,
  Bookmark,
  Bot,
  Brain,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Chrome,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudOff,
  Code,
  Command,
  Copy,
  CreditCard,
  Cpu,
  Database,
  Delete,
  Dna,
  Download,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  File,
  FileJson,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  Github,
  Globe,
  Grid3x3,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Move,
  Music,
  Navigation,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  Pencil,
  Phone,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Power,
  Printer,
  Radio,
  RefreshCw,
  RefreshCcw,
  Repeat,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  Triangle,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XSquare,
  Youtube,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  // Alert icons
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  
  // Arrow icons
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  
  // Status icons
  ban: Ban,
  check: Check,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  circle: Circle,
  info: Info,
  x: X,
  xCircle: XCircle,
  xSquare: XSquare,
  
  // Navigation icons
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  
  // Action icons
  clipboard: Clipboard,
  copy: Copy,
  download: Download,
  edit: Edit,
  edit2: Edit2,
  edit3: Edit3,
  externalLink: ExternalLink,
  link: Link,
  link2: Link2,
  paperclip: Paperclip,
  plus: Plus,
  plusCircle: PlusCircle,
  save: Save,
  share: Share,
  share2: Share2,
  trash: Trash,
  trash2: Trash2,
  upload: Upload,
  
  // UI icons
  calendar: Calendar,
  clock: Clock,
  close: X,
  filter: Filter,
  grid: Grid3x3,
  list: List,
  loader: Loader,
  loader2: Loader2,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  refresh: RefreshCw,
  refreshCcw: RefreshCcw,
  search: Search,
  settings: Settings,
  settings2: Settings2,
  sliders: Sliders,
  slidersHorizontal: SlidersHorizontal,
  spinner: Loader2,
  
  // User icons
  user: User,
  userCheck: UserCheck,
  userMinus: UserMinus,
  userPlus: UserPlus,
  userX: UserX,
  users: Users,
  
  // Communication icons
  bell: Bell,
  mail: Mail,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  phone: Phone,
  send: Send,
  
  // Media icons
  camera: Camera,
  image: Image,
  mic: Mic,
  music: Music,
  pause: Pause,
  pauseCircle: PauseCircle,
  play: Play,
  playCircle: PlayCircle,
  skipBack: SkipBack,
  skipForward: SkipForward,
  speaker: Speaker,
  video: Video,
  videoOff: VideoOff,
  volume: Volume,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  
  // File icons
  file: File,
  fileJson: FileJson,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  
  // Device icons
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  tv: Tv,
  
  // Security icons
  eye: Eye,
  eyeOff: EyeOff,
  key: Key,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  shield: Shield,
  shieldCheck: ShieldCheck,
  unlock: Unlock,
  
  // Data icons
  barChart: BarChart,
  barChart2: BarChart2,
  barChart3: BarChart3,
  database: Database,
  server: Server,
  
  // Brand icons
  chrome: Chrome,
  facebook: Facebook,
  github: Github,
  slack: Slack,
  twitter: Twitter,
  youtube: Youtube,
  
  // Specialized icons
  bot: Bot,
  brain: Brain,
  cloud: Cloud,
  cloudOff: CloudOff,
  code: Code,
  command: Command,
  cpu: Cpu,
  dna: Dna,
  globe: Globe,
  hash: Hash,
  heart: Heart,
  helpCircle: HelpCircle,
  home: Home,
  layers: Layers,
  layout: Layout,
  lifeBuoy: LifeBuoy,
  map: Map,
  mapPin: MapPin,
  mountain: Mountain,
  package: Package,
  printer: Printer,
  radio: Radio,
  shuffle: Shuffle,
  sidebar: Sidebar,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thumbsDown: ThumbsDown,
  thumbsUp: ThumbsUp,
  timer: Timer,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  triangle: Triangle,
  umbrella: Umbrella,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wifiOff: WifiOff,
  wind: Wind,
  zap: Zap,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  
  // Theme icons
  moon: Moon,
  
  // Google icon (custom SVG component)
  google: (props: React.SVGProps<SVGSVGElement>) => (
    <svg viewBox="0 0 24 24" {...props}>
      <path
        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
        fill="#4285F4"
      />
      <path
        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
        fill="#34A853"
      />
      <path
        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
        fill="#FBBC05"
      />
      <path
        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
        fill="#EA4335"
      />
    </svg>
  ),
  
  // Genomics specific icons (using existing icons)
  variant: Dna,
  analysis: Brain,
  clinical: Heart,
  report: FileText,
  pathogenic: AlertTriangle,
  benign: CheckCircle,
  vus: HelpCircle,
  
  // Activity icons
  activity: BarChart3,
  pulse: BarChart2,
} as const

export type IconName = keyof typeof Icons